[package]
name = "gomez"
version = "0.1.0"
authors = ["Petr Nevyhoštěný <petr.nevyhosteny@gmail.com>"]
description = "A pure Rust framework and implementation of (derivative-free) methods for solving nonlinear (bound-constrained) systems of equations."
documentation = "https://docs.rs/gomez/"
repository = "https://github.com/datamole-ai/gomez"
license = "MIT"
readme = "README.md"
keywords = ["nonlinear-equations", "optimization", "math", "science"]
categories = ["science", "mathematics"]
edition = "2021"

[dependencies]
nalgebra = "0.28"
rand = "0.8"
rand_distr = "0.4"
approx = "0.5"
num-traits = "0.2"
thiserror = "1"
log = "0.4"
getset = "0.1"

[dev-dependencies]
criterion = "0.3"
gsl-wrapper = { path = "gsl-wrapper" }

[[bench]]
name = "solvers"
harness = false
