[package]
name = "gomez-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
divan = "0.1.2"
gomez = { path = "..", features = ["testing"] }
gsl-wrapper = { path = "../gsl-wrapper" }

[[bench]]
name = "main"
harness = false
