name: Gomez publish

on:
  push:
    tags:
      - v*

jobs:
  rust-publish:
    name: Rust publish
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: cargo test

      - name: Publish package
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
